  on: push

  env:
    ARTIFACT_NAME: my-node-artifact
    TAG: v1.1

  name: Create Release

  jobs:
    build:
      name: Create Release
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@master

        - name: Upload the Artifact
          uses: actions/upload-artifact@v2
          with:
            name: ${{ env.ARTIFACT_NAME }}
            path: .

        - name: Create Release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ github.ref }}
            release_name: Release ${{ github.ref }}
            body: |
              Changes in this Release
              - First Change
              - Second Change
            draft: false
            prerelease: false