  on:
    push:
      branches:
        - master

  env:
    ARTIFACT_NAME: my-node-artifact
    TAG: v1.1

  name: Create Release

  jobs:
    build:
      name: Checking the Code
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@master

        - name: Upload the Artifact
          uses: actions/upload-artifact@v2
          with:
            name: ${{ env.ARTIFACT_NAME }}
            path: .

        - name: Github Tag Bump
          uses: anothrNick/github-tag-action@1.61.0
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            WITH_V: false