# example 1: on push to master
name: Bump version
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '1'

      - name: Upload the Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: .

      - name: Bump version and push tag
        uses: opspresso/action-version@master
        env:
          ROOT_GITHUB_TOKEN: ${{ secrets.ROOT_GITHUB_TOKEN }}
          WITH_V: true
