# example 1: on push to master
name: Bump version
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - name: Bump Version
        uses: opspresso/action-version@master
        env:
          ROOT_ GITHUB_TOKEN: ${{ secrets.ROOT_ GITHUB_TOKEN }}
          WITH_V: true