name: Upload-artifact

on: push:
      tags:
        - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  ARTIFACT_NAME: my-node-artifact
  TAG: v1.1

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the Code
        uses: actions/checkout@v2
        id: create_release
        uses: actions/create-release@latest
        env:
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
        with:
          tag_name: ${{ env.TAG }}
          release_name: ${{ env.ARTIFACT_NAME }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false

      - name: Upload the Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: .

